[package]
name = "zero-knowledge"
version = "0.1.0"
authors = ["Patrick Biel <p.biel@outlook.com>"]
description = "Zero Knowledge Proof Generation and Verification using STARKs"
repository = "https://github.com/libra/libra"
homepage = "https://libra.org"
license = "Apache-2.0"
publish = false
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
project-root = "0.2.2"
# Query Ropsten for Proof (Irrelevant if STARK decides to make an api to interact with SHARP)
web3 = { path = "../rust-web3-0.13.0" }
ethereum_abi = { path = "../rust-ethereum-abi-0.1.0" }
hex = "^0.3.0"
cairo-verifier = { git = "https://github.com/patrickbiel01/Cairo_Verifier", branch = "main" }
tokio = { version = "0.2.22", features = ["full"] }
